### ISSUE TITLE
Fail to commit template change

### ISSUE THREAD

**Issue by zenkchen** [kevinsteves/pan-python#13] opened 2016-12-07 00:06 UTC
The following template change failed,

commit-all template name MyTemplate

xapi.commit('<commit-all><template><name><entry name="MyTemplate"/></name></template></commit-all>', action="all")

Error is following:

File "pan-pass.py", line 31, in main
xapi.commit('<commit-all><template><name><entry name="MyTemplate"/></name></template></commit-all>', action="all")
File "/Library/Python/2.7/site-packages/pan/xapi.py", line 842, in commit
raise PanXapiError(self.status_detail)

**Comment by acstanton515** [comment] 2016-12-19 02:57
You may need to clarify on what it is you are reporting.  A commit failure does not indicate an issue with xapi.

**Comment by zenkchen** [comment] 2016-12-19 03:04
Thanks for reply. I have case open with PAN, Tac believe it is Xapi bug. Does the Xapi support " template commit"?

**Comment by acstanton515** [comment] 2016-12-19 03:39
I believe so.   You may want to visit the documentation pages for the xapi as well as the XML API guide documentation.  

cmd argument is a required argument in the latest version of xapi that I have seen.  When I attempt to commit as you have, I get below error, which shows you may have omitted an error line:

```
> my_panorama.commit('', action="all")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pan/xapi.py", line 842, in commit
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError: Missing value for parameter "cmd".
```

I cannot test so easily right now, but in my test environment we have template stack, I believe this syntax would push template changes to all devices with the example template stack name:

`<commit-all><template-stack><name>ts_generic_stack</name></template-stack></commit-all>`

Thus you would need to set cmd argument with similar XML string.

**Comment by kevinsteves** [comment] 2016-12-20 16:59
The pan.xapi commit() method will handle all "commit-all" requests.  The issue is usually the cmd= XML document.  Suggest doing something like this to get the XML.  I will close this issue.  Please contact me directly if you still have problems.

`admin@Panorama> debug cli on`
`admin@Panorama> commit-all template name foo`

The XML would be:

`<commit-all><template><name>foo</name></template></commit-all>`

**Closed by kevinsteves** 2016-12-20 16:59 UTC

**Comment by zenkchen** [comment] 2016-12-20 23:53
The fomat seems having some issue:
The real command is the following:
commit-all template force-template-values yes name Corp-OOB


With xapi, I am using the following,
 xapi.commit('<commit-all><template><name><entry name="Corp-OOB"/></name></template></commit-all>', action="all")
Error is below

  File "test.py", line 29, in main
    xapi.commit('<commit-all><template><name><entry name="Corp-OOB"/></name></template></commit-all>', action="all")
  File "/Library/Python/2.7/site-packages/pan/xapi.py", line 842, in commit
    raise PanXapiError(self.status_detail)
pan.xapi.PanXapiError:  commit-all -> template -> name is invalid
